# Generated by Django 5.1.6 on 2025-03-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_athlete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.personal')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.athlete')),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.personal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainy.plan')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.athlete')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('workouts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainy.workout')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
    ]
