# Generated by Django 5.1.6 on 2025-03-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Exercicie',
                'verbose_name_plural': 'Exercicies',
            },
        ),
        migrations.CreateModel(
            name='Exercicies_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('series', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainy.division')),
                ('exercicie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainy.exercicies')),
            ],
            options={
                'verbose_name': 'Exercicie Division',
                'verbose_name_plural': 'Exercicies Divisions',
            },
        ),
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('divisions', models.ManyToManyField(to='trainy.division')),
                ('exercicies', models.ManyToManyField(to='trainy.exercicies')),
            ],
            options={
                'verbose_name': 'Muscle',
                'verbose_name_plural': 'Muscles',
            },
        ),
    ]
