# Generated by Django 5.1.6 on 2025-03-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0002_exercicies_exercicies_division_muscles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscles',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='muscles',
            name='exercicies',
        ),
    ]
