# Generated by Django 5.1.6 on 2025-03-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0003_remove_muscles_divisions_remove_muscles_exercicies'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicies',
            name='muscle',
            field=models.ManyToManyField(to='trainy.muscles'),
        ),
    ]
