# Generated by Django 5.1.6 on 2025-03-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0004_exercicies_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='muscle',
            field=models.ManyToManyField(to='trainy.muscles'),
        ),
    ]
