# Generated by Django 5.1.6 on 2025-03-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0005_division_muscle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='workouts',
        ),
        migrations.AddField(
            model_name='division',
            name='workout',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='trainy.workout'),
            preserve_default=False,
        ),
    ]
