# Generated by Django 5.1.6 on 2025-03-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainy', '0006_remove_division_workouts_division_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='muscle',
            new_name='muscles',
        ),
    ]
