# Generated by Django 5.1.6 on 2025-03-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='apresentacao',
            new_name='personalcol',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='especialidade',
            new_name='specialty',
        ),
    ]
